routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\KategoriController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\Buku_TamuController;
// use App\Http\Controllers\BeritaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\TeknikController;
use App\Http\Controllers\Storage;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontendController::class, 'index']);
Route::post('/', [FrontendController::class, 'store'])->name('frontend.capture');
Route::get('teknik', [TeknikController::class, 'index'])->name('teknik');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {    
    
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('user', UserController::class);
    // Route::get('kategori', [KategoriController::class, 'index'])->name('kategori');
    // Route::get('kategori/add', [KategoriController::class, 'create'])->name('kategori.create');
    // Route::resource('kategori', KategoriController::class);
    // Route::post('/kategori/{id}', [KategoriController::class, 'update'])->name('kategori.update');
    // route::get('/kategori/{id}/delete', [KategoriController::class, 'destroy']);

    // Route::resource('berita', BeritaController::class);
    // Route::post('/berita/{id}', [BeritaController::class, 'update'])->name('berita.update');
    // route::get('/berita/{id}/delete', [BeritaController::class, 'destroy']);

    Route::resource('agenda', AgendaController::class);
    Route::post('/agenda/{id}', [AgendaController::class, 'update'])->name('agenda.update');
    Route::get('/agenda/{id}/delete', [AgendaController::class, 'destroy']);
    Route::get('/agendacetak', [AgendaController::class, 'cetak'])->name('agenda.cetak');

    Route::resource('buku_tamu', Buku_TamuController::class);
    Route::post('/buku_tamu/{id}', [Buku_TamuController::class, 'update'])->name('buku_tamu.update');
    Route::get('/buku_tamu/{id}/delete', [Buku_TamuController::class, 'destroy']);
    Route::get('/bukucetak', [Buku_TamuController::class, 'cetak'])->name('tamu.cetak');

    Route::resource('slider', SliderController::class);
    Route::post('/slider/{id}', [SliderController::class, 'update'])->name('slider.update');
    Route::get('/slider/{id}/delete', [SliderController::class, 'destroy']);    

    Route::resource('galeri', GaleriController::class);
    Route::post('/galeri/{id}', [GaleriController::class, 'update'])->name('galeri.update');
    route::get('/galeri/{id}/delete', [GaleriController::class, 'destroy']);

    Route::resource('footer', FooterController::class);
    Route::post('/footer/{id}', [FooterController::class, 'update'])->name('footer.update');
    Route::get('/footer/{id}/delete', [FooterController::class, 'destroy']);


    // Route::get('/berita', function () {
    //     return view('berita.index');
    // })->name('berita');
    
});

app/Models/Agenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $table='agenda';
    protected $primaryKey='id';
    protected $fillable=[
        'nama_agenda', 'jenis', 'tanggal', 'waktu', 'status'
    ];
    use HasFactory;
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Agenda;
use Jenssegers\Agent\Facades\Agent;
use Illuminate\Support\Facades\Storage;
use PDF;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agenda = Agenda::all();
        return view('agenda.index', compact('agenda'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $agenda = Agenda::all();
        return view('agenda.create', compact('agenda'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Agenda::create([
            'nama_agenda' => $request->nama_agenda,
            'jenis' => $request->jenis,
            'tanggal' => $request->tanggal,
            'waktu' => $request->waktu,
            'status' => $request->status,
        ]);
        return redirect('agenda')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agenda = Agenda::where('status', 1)->orderBy('id','ASC')->get();
        return view('agenda.update', compact('agenda'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $agenda = Agenda::find($id);
        $agenda->update($request->all());
        return redirect('agenda')->with('success', 'Data Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $agenda = Agenda::find($id);
        $agenda->delete();
        return redirect('agenda')->with('success', 'Data Berhasil Dihapus');
    }

    public function cetak()
    {
        $agenda = Agenda::all();
        view()->share('agenda', $agenda);
        $pdf = PDF::loadview('agenda.cetak');
        return $pdf->download('agenda.pdf');
    }
}

resources/views/agenda/cetak.blade.php
<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4e73df;
  color: white;
}
</style>
</head>
<body>

<h3>Data Agenda RRI Sumenep</h3>

<table id="customers">
  <tr>
    <th>No</th>
    <th>Kategori</th>
    <th>Nama Agenda</th>
    <th>Tanggal</th>
    <th>Waktu</th>
  </tr>
  @php $i=1 @endphp
  @foreach ($agenda as $data)
  <tr>
    <td class="text-center" >{{ $i++ }}</td>
    <td>{{ $data->jenis }}</td>
    <td>{{ $data->nama_agenda }}</td>
    <td class="text-center">{{ $data->tanggal }}</td>
    <td>{{ $data->waktu }}</td>
  </tr>
  @endforeach
  
</table>

</body>
</html>

resources/views/agenda/create.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Agenda</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('agenda.store') }}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="group">
            <label for="nama_agenda">Nama Agenda</label>
            <input type="text" name="nama_agenda" class="form-control" id="nama_agenda">
          </div>
          <div class="group">
            <label for="jenis">Jenis Agenda</label>
            <select class="default-select wide form-control" name="jenis">
                    <option selected>Select Agenda</option>
                    <option value="Agenda Tahunan">Agenda Tahunan</option>
                    <option value="Agenda Bulanan">Agenda Bulanan</option>
                    <option value="Agenda Mingguan">Agenda Mingguan</option>
            </select>
          </div>
          <div class="group">
            <label for="tanggal">Tanggal</label>
            <input type="date" name="tanggal" class="form-control" id="tanggal">
          </div>
          
          <div class="group">
            <label for="waktu">Waktu</label>
            <input type="time" name="waktu" placeholder="isi" class="form-control"> 
          </div>
          <div class="group">
            <label for="status">Status</label>
            <select class="default-select wide form-control" name="status">
                    <option value="1">Active</option>
                    <option value="0">Draf</option>
            </select>
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

resources/views/agenda/index.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

    <!-- DataTales Example -->
      <div class="card shadow mb-4">
          <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Tabel Agenda</h6>
              <div class="button text-end" style="float: right;">
              <a href="{{ route('agenda.cetak') }}" class="btn btn-success" ><i class="bi bi-printer" style="margin-right: 5px;"></i>cetak</a>
              <a href="" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >+ Tambah Agenda</a>
              </div>
          </div>
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0" >
                      <thead class="text-center">
                          <tr>
                            <th style="width: 2%">No.</th>
                            <th>Kategori</th>
                            <th style="width: 15%">Nama Agenda</th>
                            <th style="width: 15%">Tanggal </th>
                            <th style="width: 20%">Waktu</th>
                            <th style="width: 13%">Status</th>
                            <th style="width: 14%">Action</th>
                          </tr>
                      </thead>
                      <tbody>
                        @php $i=1 @endphp
                        @foreach ($agenda as $data)
                       
                          <tr>
                              <td class="text-center" >{{ $i++ }}</td>
                              <td>{{ $data->jenis }}</td>
                              <td>{{ $data->nama_agenda }}</td>
                              <td class="text-center">{{ $data->tanggal }}</td>
                              <td>{{ $data->waktu }}</td>
                              <td>
                                @if($data->status == 1)
                                Active
                              @else
                                Draf
                              @endif
                              </td>
                              <td class="text-center">
                                <a href="#" class="btn btn-warning" data-toggle="modal" data-target="#updateModal{{$data->id}}"><I class="bi bi-pencil-square"></I></a>
                                <a href="" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $data->id }}"><i class="bi bi-trash"></i></a>
                              </td>
                          </tr>
                               
                        @endforeach
                          
                      </tbody>
                  </table>
              </div>
          </div>
      </div>

  </div>

  <!-- Modal -->
  @foreach ($agenda as $data)
<div class="modal fade" id="deleteModal{{ $data->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Agenda</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <p class="text-center">Are you sure want to delete?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="/agenda/{{$data->id}}/delete" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
@endforeach


  @include('sweetalert::alert')
  @include('agenda.create')
  @include('agenda.update')
  <!-- /.container-fluid -->
@endsection

resources/views/agenda/update.blade.php
<!-- Modal -->
@foreach ($agenda as $data)
<div class="modal fade" id="updateModal{{ $data->id }}" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Update Agenda</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('agenda.update', $data->id)}}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="group">
            <label for="nama_agenda">Nama Agenda</label>
            <input type="text" name="nama_agenda" class="form-control" id="nama_agenda" value="{{$data->nama_agenda}}">
          </div>
          <div class="group">
            <label for="jenis">Jenis Agenda</label>
            <select class="default-select wide form-control" name="jenis">
                    <option selected>{{$data->jenis}}</option>
                    <option value="Agenda Tahunan">Agenda Tahunan</option>
                    <option value="Agenda Bulanan">Agenda Bulanan</option>
                    <option value="Agenda Mingguan">Agenda Mingguan</option>
            </select>
          </div>
          <div class="group">
            <label for="tanggal">Tanggal</label>
            <input type="date" name="tanggal" class="form-control" id="tanggal" value="{{$data->tanggal}}">
          </div>
          
          <div class="group">
            <label for="waktu">Waktu</label>
            <input type="time" name="waktu" placeholder="isi" class="form-control" value="{{$data->waktu}}">
          </div>
          <div class="group">
            <label for="status">Status</label>
            <select class="default-select wide form-control" name="status">
                    <option value="1" {{$data->status == '1' ? 'selected' : ''}}>Active</option>
                    <option value="0" {{$data->status == '0' ? 'selected' : ''}}>Draf</option>
            </select>
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endforeach