routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\KategoriController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\Buku_TamuController;
// use App\Http\Controllers\BeritaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\TeknikController;
use App\Http\Controllers\Storage;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontendController::class, 'index']);
Route::post('/', [FrontendController::class, 'store'])->name('frontend.capture');
Route::get('teknik', [TeknikController::class, 'index'])->name('teknik');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {    
    
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('user', UserController::class);
    // Route::get('kategori', [KategoriController::class, 'index'])->name('kategori');
    // Route::get('kategori/add', [KategoriController::class, 'create'])->name('kategori.create');
    // Route::resource('kategori', KategoriController::class);
    // Route::post('/kategori/{id}', [KategoriController::class, 'update'])->name('kategori.update');
    // route::get('/kategori/{id}/delete', [KategoriController::class, 'destroy']);

    // Route::resource('berita', BeritaController::class);
    // Route::post('/berita/{id}', [BeritaController::class, 'update'])->name('berita.update');
    // route::get('/berita/{id}/delete', [BeritaController::class, 'destroy']);

    Route::resource('agenda', AgendaController::class);
    Route::post('/agenda/{id}', [AgendaController::class, 'update'])->name('agenda.update');
    Route::get('/agenda/{id}/delete', [AgendaController::class, 'destroy']);
    Route::get('/agendacetak', [AgendaController::class, 'cetak'])->name('agenda.cetak');

    Route::resource('buku_tamu', Buku_TamuController::class);
    Route::post('/buku_tamu/{id}', [Buku_TamuController::class, 'update'])->name('buku_tamu.update');
    Route::get('/buku_tamu/{id}/delete', [Buku_TamuController::class, 'destroy']);
    Route::get('/bukucetak', [Buku_TamuController::class, 'cetak'])->name('tamu.cetak');

    Route::resource('slider', SliderController::class);
    Route::post('/slider/{id}', [SliderController::class, 'update'])->name('slider.update');
    Route::get('/slider/{id}/delete', [SliderController::class, 'destroy']);    

    Route::resource('galeri', GaleriController::class);
    Route::post('/galeri/{id}', [GaleriController::class, 'update'])->name('galeri.update');
    route::get('/galeri/{id}/delete', [GaleriController::class, 'destroy']);

    Route::resource('footer', FooterController::class);
    Route::post('/footer/{id}', [FooterController::class, 'update'])->name('footer.update');
    Route::get('/footer/{id}/delete', [FooterController::class, 'destroy']);


    // Route::get('/berita', function () {
    //     return view('berita.index');
    // })->name('berita');
    
});

app/Models/Galeri.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Galeri extends Model
{
    protected $table= 'galeri';
    protected $primaryKey= 'id';
    protected $fillable=[
        'judul', 'image', 'keterangan'
    ];
    use HasFactory;
}

app/Http/Controllers/GaleriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Galeri;
use Illuminate\Support\Facades\Storage;

class GaleriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galeri = Galeri::all();
        return view('galeri.index', compact('galeri'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('galeri.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Galeri::create([
            'judul' => $request->judul,
            'image' => $request->file('image')->store('galeri'),
            'keterangan' => $request->keterangan,
        ]);
        return redirect('galeri')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $galeri = Galeri::find($id);

        return view('galeri.update', compact('galeri'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (empty($request->file('image'))) {
            $galeri = Galeri::find($id);
            $galeri->update([
            'judul' => $request->judul,
            'keterangan' => $request->keterangan,
            ]);
            return redirect('galeri')->with('success', 'Data Berhasil DiUpdate');
        } else {
            $galeri = Galeri::find($id);
            Storage::delete($galeri->image);
            $galeri->update([
            'judul' => $request->judul,
            'image' => $request->file('image')->store('galeri'),
            'keterangan' => $request->keterangan,
            ]);
            return redirect('galeri')->with('success', 'Data Berhasil DiUpdate');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $galeri = Galeri::find($id);
        $galeri->delete();
        return redirect('galeri')->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/galeri/create.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Galeri</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('galeri.store') }}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="group">
            <label for="judul">Judul Gambar</label>
            <input type="text" name="judul" class="form-control" id="judul">
          </div>
          <div class="group">
            <label for="image">Gambar</label>
            <input type="file" name="image" class="form-control" id="image">
          </div>
          <div class="group">
            <label for="keterangan">Keterangan Gambar</label>
            <input type="text" name="keterangan" class="form-control" id="keterangan">
          </div>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

resources/views/galeri/index.blade.php
@extends('layouts.master')
@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

    <!-- DataTales Example -->
      <div class="card shadow mb-4">
          <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Tabel Galeri</h6>
              <a href="" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="float: right;">+ Tambah Kategori</a>
          </div>
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0" >
                      <thead class="text-center">
                          <tr>
                            <th style="width: 2%">No.</th>
                            <th style="width: 25%">Judul </th>
                            <th style="width:19% ">Image</th>
                            <th style="width:30% ">Keterangan</th>
                            <th style="width:14%">Action</th>
                              
                          </tr>
                      </thead>
                      <tbody>
                        @php $i=1 @endphp
                        @foreach ($galeri as $data )
                            
                          <tr>
                              <td class="text-center" >{{ $i++ }}</td>
                              <td>{{ $data->judul }}</td>
                              <td>
                                <img src="{{ asset('upload/'.$data->image) }}" width="80px">
                              </td>
                              <td>{{ $data->keterangan }}</td>
                              <td class="text-center">
                                <a href="" class="btn btn-warning" data-toggle="modal" data-target="#updateModal{{$data->id}}"><i class="bi bi-pencil-square"></i></a>
                                <a href="" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $data->id }}"><i class="bi bi-trash"></i></a>
                              </td>
                          </tr>

                        @endforeach 
                          
                      </tbody>
                  </table>
              </div>
          </div>
      </div>

  </div>

   <!--Delete Modal -->
  @foreach ($galeri as $data )
<div class="modal fade" id="deleteModal{{ $data->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Galeri</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
      <p class="text-center">Are you sure want to delete this galeri?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="/galeri/{{$data->id}}/delete" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
@endforeach



  @include('sweetalert::alert')
  @include('galeri.create')
  @include('galeri.update')
  <!-- /.container-fluid -->
@endsection

resources/views/galeri/update.blade.php
@foreach ($galeri as $data )
<div class="modal fade" id="updateModal{{ $data->id }}" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Update Galeri</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('galeri.update', $data->id)}}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="group">
            <label for="judul">Judul Gambar</label>
            <input type="text" name="judul" class="form-control" id="judul" value="{{$data->judul}}">
          </div>
          <div class="group">
            <label for="image">Gambar</label>
            <input type="file" name="image" class="form-control" id="image">
            <img src="{{asset('upload/' .$data->image)}}">
          </div>
          <div class="group">
            <label for="keterangan">Keterangan Gambar</label>
            <input type="text" name="keterangan" class="form-control" id="keterangan" value="{{$data->keterangan}}">
          </div>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endforeach