routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
// use App\Http\Controllers\KategoriController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\Buku_TamuController;
// use App\Http\Controllers\BeritaController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\TeknikController;
use App\Http\Controllers\Storage;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontendController::class, 'index']);
Route::post('/', [FrontendController::class, 'store'])->name('frontend.capture');
Route::get('teknik', [TeknikController::class, 'index'])->name('teknik');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {    
    
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('user', UserController::class);
    // Route::get('kategori', [KategoriController::class, 'index'])->name('kategori');
    // Route::get('kategori/add', [KategoriController::class, 'create'])->name('kategori.create');
    // Route::resource('kategori', KategoriController::class);
    // Route::post('/kategori/{id}', [KategoriController::class, 'update'])->name('kategori.update');
    // route::get('/kategori/{id}/delete', [KategoriController::class, 'destroy']);

    // Route::resource('berita', BeritaController::class);
    // Route::post('/berita/{id}', [BeritaController::class, 'update'])->name('berita.update');
    // route::get('/berita/{id}/delete', [BeritaController::class, 'destroy']);

    Route::resource('agenda', AgendaController::class);
    Route::post('/agenda/{id}', [AgendaController::class, 'update'])->name('agenda.update');
    Route::get('/agenda/{id}/delete', [AgendaController::class, 'destroy']);
    Route::get('/agendacetak', [AgendaController::class, 'cetak'])->name('agenda.cetak');

    Route::resource('buku_tamu', Buku_TamuController::class);
    Route::post('/buku_tamu/{id}', [Buku_TamuController::class, 'update'])->name('buku_tamu.update');
    Route::get('/buku_tamu/{id}/delete', [Buku_TamuController::class, 'destroy']);
    Route::get('/bukucetak', [Buku_TamuController::class, 'cetak'])->name('tamu.cetak');

    Route::resource('slider', SliderController::class);
    Route::post('/slider/{id}', [SliderController::class, 'update'])->name('slider.update');
    Route::get('/slider/{id}/delete', [SliderController::class, 'destroy']);    

    Route::resource('galeri', GaleriController::class);
    Route::post('/galeri/{id}', [GaleriController::class, 'update'])->name('galeri.update');
    route::get('/galeri/{id}/delete', [GaleriController::class, 'destroy']);

    Route::resource('footer', FooterController::class);
    Route::post('/footer/{id}', [FooterController::class, 'update'])->name('footer.update');
    Route::get('/footer/{id}/delete', [FooterController::class, 'destroy']);


    // Route::get('/berita', function () {
    //     return view('berita.index');
    // })->name('berita');
    
});

app/Models/Footer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Footer extends Model
{
    protected $table= 'footer';
    protected $primaryKey= 'id';
    protected $fillable= [
        'deskripsi_footer', 'status',
    ];
    use HasFactory;
}

app/Http/Controllers/FooterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Footer;

class FooterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $footer = Footer::all();
        return view('footer.index', compact('footer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('footer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Footer::create([
            'deskripsi_footer'=> $request->deskripsi_footer,
            'status'=> $request->status,
        ]);
        return redirect('footer')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $footer = Footer::find($id);
        return view('footer.update', compact('footer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $footer = Footer::find($id);
        $footer->update($request->all());
        return redirect('footer')->with('succes', 'Data Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $footer = Footer::find($id);
        $footer->delete();
        return redirect('footer')->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/footer/create.blade.php

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Footer</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{ route('footer.store') }}" method="POST">
          @csrf
          <div class="group">
            <label for="deskripsi_footer">Deskripsi footer</label>
            <textarea name="deskripsi_footer" id="deskripsi_footer" placeholder="isi" class="form-control"></textarea>
          </div>
          <div class="group">
            <label for="status">Status</label>
            <select name="status" id="status" class="form-control">
              <option value="1">Publish</option>
              <option value="0">Tidak Publish</option>
            </select>

          </div>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

resources/views/footer/index.blade.php
@extends('layouts.master')
@section('content')
   <!-- Begin Page Content -->
   <div class="container-fluid">

    <!-- DataTales Example -->
      <div class="card shadow mb-4">
          <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Tabel Footer</h6>
              <a href="" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="float: right;">+ Tambah Kategori</a>
          </div>
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-bordered " id="dataTable" width="100%" cellspacing="0" >
                      <thead class="text-center">
                          <tr>
                            <th style="width: 2%">No.</th>
                            <th style="width:59%">Deskripsi Footer</th>
                            <th style="width: 15%">Status</th>
                            <th style="width: 14%">Action</th>
                          </tr>
                      </thead>
                      <tbody>
                        @php $i=1; @endphp
                        @foreach ($footer as $data )
                            
                          <tr>
                              <td class="text-center" >{{ $i++ }}</td>
                              <td>{{ $data->deskripsi_footer }}</td>
                              <td class="text-center">{{ ($data->status == 1) ? "publish" : "tidak publish" }}</td>
                              <td class="text-center" >
                                <a href="#" class="btn btn-warning" data-toggle="modal" data-target="#updateModal{{$data->id}}"><i class="bi bi-pencil-square"></i></a>
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $data->id }}"><I class="bi bi-trash"></I></a>
                              </td>
                          </tr>
                          
                        @endforeach 
                      </tbody>
                  </table>
              </div>
          </div>
      </div>

  </div>

   <!-- Modal -->
   @foreach ($footer as $data )
   <div class="modal fade" id="deleteModal{{ $data->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title" id="deleteModalLabel">Delete Footer</h5>
           <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
         </div>
         <div class="modal-body">
         <p class="text-center">Are you sure want to delete?</p>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
           <a href="/footer/{{$data->id}}/delete"  type="submit" class="btn btn-danger">Delete</a>
         </div>
       </div>
     </div>
   </div>
   @endforeach

@include('sweetalert::alert')
@include('footer.create')
@include('footer.update')
@endsection

resources/views/footer/update.blade.php

<!-- Modal -->
@foreach ($footer as $data )
<div class="modal fade" id="updateModal{{ $data->id }}" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateModalLabel">Update Footer</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('footer.update', $data->id)}}" method="POST" enctype="multipart/form-data">
          @csrf
          <div class="group">
            <label for="deskripsi_footer">Deskripsi Footer</label>
            <textarea name="deskripsi_footer" id="deskripsi_footer" class="form-control" >{{$data->deskripsi_footer}}</textarea>
            
          </div>
          <div class="group">
            <label for="status">Status</label>
            <select class="form-control" name="status" id="status">
              <option value="1"{{ (1 == $data->status) ? 'selected' : '' }}>Publish</option>
              <option value="0"{{ (0 == $data->status) ? 'selected' : '' }}>Tidak Publish</option>
            </select>
          </div>
        
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
@endforeach 